### ISSUE TITLE
Don't generate binary

### ISSUE THREAD

**Issue by piranna** [keindev/standard-shared-config#632]
Instead of generating an executable, take a more "traditional" aproach like `eslint` or `jest` shared configs and plugins, and just export them, being the binary an independent dependency. This could also make it easier to detect and fix conflicts when extending from several shared configs. Files can be exported on the generated package by using the `exports` field in the `package.json` file, so we could also fully remove the `.config` folder and use project one, or whatever it's defined in `package.json` file.

**Comment by keindev** [comment]
> Instead of generating an executable, take a more "traditional" aproach like `eslint` or `jest` shared configs and plugins, and just export them, being the binary an independent dependency. This could also make it easier to detect and fix conflicts when extending from several shared configs. Files can be exported on the generated package by using the `exports` field in the `package.json` file, so we could also fully remove the `.config` folder and use project one, or whatever it's defined in `package.json` file.

What operating system do they not work on? Do you have an error or are you talking about the initial installation / initialization of the configuration?

**Comment by piranna** [comment]
On the initial installation, files in `bin/` folder doesn't have execution bit, so they are not executable. I'm using Ubuntu Linux 23.04.

**Comment by keindev** [comment]
After installation, you need to add `prepare: "config script"` to package.json. This script will be called after each subsequent installation of packages (this is described in the [readme](https://blog.typicode.com/husky-git-hooks-autoinstall/)).

This approach is used in Husky, and I like it more than post-installation manipulations. (why [here](https://blog.typicode.com/husky-git-hooks-autoinstall/))

If I understand the problem correctly.

**Comment by piranna** [comment]
No, that's not the problem, in fact this is not related to the bins, not sure why you merged both issues. Here what I'm asking for is about instead of a build process that generates a package with a custom executable file that will be executed on prepare like husky does, have a generic runner package that's the one executed on prepare, that reads and apply the content of a config file or package, similar to eslint or jest or several other project with their shared-config packages. This makes It easier to distribute and combine multiple configurations, since since they can extend the config of the final project in an optimized way, instead of executing multiple binaries that can overwrite the changes of the previous ones.

**Comment by keindev** [comment]
Configurations should not have common/overlapping files that are not combined through a merge rule. Therefore, the order in which they are used should not affect the structure, otherwise it is better to make 1 package with the configuration and not split it into several parts.

This package does not solve the problem of dependencies of configuration packages on one another and their sequential use (simply because it does not imply such use).

**Comment by piranna** [comment]
Making config packages not having common/overlapping files makes it simpler by evading the merge problem, but also makes the system a lot less flexible, and having a single package with all the configs ready to use it's suboptimal since you can't have common and base configs. But the main problem I'm facing is about having a common base config, and later having per-project customizations. That's why I say having a declarative approach instead of a imperative one, by having configs defined as a static data structure instead of generating a builder command, it's simpler to work with and more flexible to use.
