### ISSUE TITLE
Define scripts as object

### ISSUE THREAD

**Issue by piranna** [keindev/standard-shared-config#660]
Instead of define the scripts as a list, allow to define it as an object with an hierarchy of commands, this makes it easier to maintain when there's a lot of scripts commands that need to be included.

**Comment by keindev** [comment]
In this case, I don't want to deviate from the `package.json / scripts`  model - it's just a list of commands.

To solve this problem, it is better to use special packages (in the case of a hierarchy of commands or a non-linear dependence of one command on another)

**Comment by piranna** [comment]
The thing is the same, define the scripts as an hierarchy, that later would be flattened by joining paths as prefixes with `:` as it's common, instead of having to define the prefix in all the entries. This can make it more easy to maintain since they would be grouped, we don't need to stick to the same format used in `package.json` in on our files.
